language: node_js
node_js:
- node
- '6'
deploy:
  provider: heroku
  api_key:
    secure: SmQL0ywSBCn+1cBz5KZPeU88tqINUzMrYqdeh/Elf1HEfUVx3VLA0v1ZtD+J5jJRfDwxi//z0mSykHcdNZS7OCEzhEOlN5Q1oI9GWjIJuNP6voxnwjkb64xrLIGtPfTR6HAtnQwS9WFrVNo7+eKjlaa8D4gIPd11vuV1Bma0cQtSyBxUSN2T4oC/DFly+Uy0cK6fCuj2xHd68zYnujj6d85z9njBZQ4cY1cFyvZ0STdDbKNdfgqPQglsAfhZcSQWXDsp8KC3lyg2rmhWUE4kY3ggyDqeJH5f3Ef+HyELDH/c85i9Wz8HajF6V4JU3Fz4BSVpFLicYb6uJrG9dp7nEDZ/aSac0gt3JaVNjr/ImImwzcl1wwFmt6jSoclCx9c28eTXDBrUzDnHoD2WbPCasmftbqxNjXMmnIqjhX0QGPnEoyoBeyxYx/q5PCF+rprf5cbbbuDj9feY2Q5QiyPNvQRbERZ3DIh0wO43yQnmjpZ+cVaJXS6cgu75jmEZKTIizeM4rzeCjJML+BKsghTNx0uPnggRCQnejv9Rr0GpS8YaFHLNvo5EnyGDJ4Q833lSDnWznTp5napKtCs+lQaWfHwKdJZyGC3duzfBpalih4gdFgrL1At9vXAdFUNPbWYNs35UM3yJj7QcyGnbTEjjhkmupoEU3Fm1d5tMnu9mKTc=
  app: chipin-api-dev
  on:
    repo: Krinto/ChipIn-Api
