language: node_js
node_js:
- node
- '6'
deploy:
  provider: heroku
  api_key:
    secure: hf42JjyQ8Dd/shlv2tpqk8wUaqoBWIdSY90puvuIGOFXk2EKRcwjA+KteRD1ZNbEa5hN/MMfui0Y2P9Tcu0S/8RL3ixZtmEpGD+7QX7SGewtqNazGerIDY4mT1TmXDMFRtcJuLEx9tyxzx+sGE1opoUbydvMN5032fcFlDjzu+AY+3tmfzsN4x333Cvp17Om60qOuLlPoTy2+FGIZT8bpRmsfpEomk2b1vBbmbwX6O+DHl+rqBEPD4XHk4Tzc9sxep8nUz5Ju9A08NVF5pVPia6HU8swACda6All6Rl50v6L/zJoZ077G6Hl95aWvc2V0WSnB5M0UCUmWrBKq8qZusZS63n8vwQxlCE90ksJGYOz/+imDSXQ8MzYur2upTI9vckpyjO9Yll1gFseJkHfrBuszUdk0cGrPvite7qvu9v3ssNdadf1VQofqpLaqEu7VwSz3EBGiPrbg8rSENoMFskkBWW/To0rFaZUi34B41xd3zp/3epLGSvww2qR8S5bkmJT+fx4fOsS1awrEbTbj9gw5aR0lL3zgGjzjf8GJdEz/Pwdbc/CkpvtaPG6kpmed/o1a3pCKTp10aWRP+q7mzwFD2jIsWEo8J/80i+UPy1gF+UAWFV6RBYyr7TigE/BsLh2Eqei6Iq47MsxMMCe3WCYCRLHyD23p+ZCdXfUvHM=
  app: chipin-api-dev
  on:
    repo: Krinto/ChipIn-Api
